/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.frontend.vista;

/**
 *
 * @author German
 */
public class AbrirMenu extends javax.swing.JFrame {

    /**
     * Creates new form AbrirMenu
     */
    public AbrirMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuItemAdministrarUsuarios = new javax.swing.JMenuItem();
        jMenuActivos = new javax.swing.JMenu();
        jMenuContabilidad = new javax.swing.JMenu();
        jMenuItemTipodeCuenta = new javax.swing.JMenuItem();
        jMenuItemCuentas = new javax.swing.JMenuItem();
        jMenuItemComprobantes = new javax.swing.JMenuItem();
        jMenuItemBalanceGeneral = new javax.swing.JMenuItem();
        jMenuItemEstadodeResultados = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");

        jMenuUsuarios.setText("Usuarios");
        jMenuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuariosActionPerformed(evt);
            }
        });

        jMenuItemAdministrarUsuarios.setText("Administrar Usuarios");
        jMenuItemAdministrarUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemAdministrarUsuariosMousePressed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemAdministrarUsuarios);

        jMenuBar1.add(jMenuUsuarios);

        jMenuActivos.setText("Activos");
        jMenuBar1.add(jMenuActivos);

        jMenuContabilidad.setText("Contabilidad");
        jMenuContabilidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuContabilidadMousePressed(evt);
            }
        });

        jMenuItemTipodeCuenta.setText("Tipo de cuenta");
        jMenuItemTipodeCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemTipodeCuentaMousePressed(evt);
            }
        });
        jMenuContabilidad.add(jMenuItemTipodeCuenta);

        jMenuItemCuentas.setText("Cuentas");
        jMenuItemCuentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemCuentasMousePressed(evt);
            }
        });
        jMenuContabilidad.add(jMenuItemCuentas);

        jMenuItemComprobantes.setText("Comprobantes");
        jMenuItemComprobantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemComprobantesMousePressed(evt);
            }
        });
        jMenuContabilidad.add(jMenuItemComprobantes);

        jMenuItemBalanceGeneral.setText("Balance general");
        jMenuContabilidad.add(jMenuItemBalanceGeneral);

        jMenuItemEstadodeResultados.setText("Estado de resultados");
        jMenuContabilidad.add(jMenuItemEstadodeResultados);

        jMenuBar1.add(jMenuContabilidad);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuariosActionPerformed
        //new AdministrarUsuarios().setVisible(true);
    }//GEN-LAST:event_jMenuUsuariosActionPerformed

    private void jMenuItemAdministrarUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemAdministrarUsuariosMousePressed
        new AdministrarUsuarios().setVisible(true);
    }//GEN-LAST:event_jMenuItemAdministrarUsuariosMousePressed

    private void jMenuContabilidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuContabilidadMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuContabilidadMousePressed

    private void jMenuItemTipodeCuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemTipodeCuentaMousePressed
        new TipodeCuenta().setVisible(true);
    }//GEN-LAST:event_jMenuItemTipodeCuentaMousePressed

    private void jMenuItemCuentasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCuentasMousePressed
        new Cuenta().setVisible(true);
    }//GEN-LAST:event_jMenuItemCuentasMousePressed

    private void jMenuItemComprobantesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemComprobantesMousePressed
        new ComprobanteContable().setVisible(true);
    }//GEN-LAST:event_jMenuItemComprobantesMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbrirMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbrirMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbrirMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbrirMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbrirMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuActivos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuContabilidad;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAdministrarUsuarios;
    private javax.swing.JMenuItem jMenuItemBalanceGeneral;
    private javax.swing.JMenuItem jMenuItemComprobantes;
    private javax.swing.JMenuItem jMenuItemCuentas;
    private javax.swing.JMenuItem jMenuItemEstadodeResultados;
    private javax.swing.JMenuItem jMenuItemTipodeCuenta;
    private javax.swing.JMenu jMenuUsuarios;
    // End of variables declaration//GEN-END:variables
}
