/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.frontend.vista;

import com.mycompany.frontend.controlador.CuentaControlador;
import com.mycompany.frontend.modelo.Cuenta;
import com.mycompany.frontend.modelo.TipoCuenta;
import com.mycompany.frontend.controlador.TipoCuentaControlador;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author German
 */
public class Cuentas extends javax.swing.JFrame {
    
    private CuentaControlador controlador;
    private TipoCuentaControlador controladorT;
    
    /**
     * Creates new form Cuenta
     */
    public Cuentas() {
        initComponents();
        controlador = new CuentaControlador();
        controladorT = new TipoCuentaControlador();
        cargarCuentas();
        cargarTipoCuentas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxCodigoContable = new javax.swing.JComboBox<>();
        jComboBoxNombreCuenta = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxTipodeCuenta = new javax.swing.JComboBox<>();
        jButtonNuevo = new javax.swing.JButton();
        jButtonLeer = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCuenta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Plan de cuentas");

        jLabel1.setText("Código contable");

        jComboBoxCodigoContable.setEditable(true);

        jComboBoxNombreCuenta.setEditable(true);

        jLabel2.setText("Nombre de la cuenta:");

        jLabel3.setText("Tipo de Cuenta:");

        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        jButtonLeer.setText("Leer");
        jButtonLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeerActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jTableCuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo contable", "Nombre de la Cuenta", "Tipo de cuenta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCuenta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxCodigoContable, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxNombreCuenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxTipodeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jButtonNuevo)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonLeer)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEliminar)))
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxCodigoContable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxNombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxTipodeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevo)
                    .addComponent(jButtonLeer)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonEliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeerActionPerformed
        // TODO add your handling code here:
        cargarCuentas();
    }//GEN-LAST:event_jButtonLeerActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        String codigoContable = (String) jComboBoxCodigoContable.getSelectedItem();
        String nombreCuenta = (String) jComboBoxNombreCuenta.getSelectedItem();
        String nombreTipoCuenta = (String) jComboBoxTipodeCuenta.getSelectedItem();
        int codTipoCuenta = controladorT.obtenerCodTipoCuenta2(nombreTipoCuenta);
        System.out.println("eL COD TIPO CTA ES "+codTipoCuenta);
        
        if (codigoContable.isEmpty() || nombreCuenta.isEmpty() || nombreTipoCuenta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben estar completos.");
        } else {
            Cuenta cuentaExistente = controlador.leerCuenta(codigoContable);
            if (cuentaExistente != null) {
                JOptionPane.showMessageDialog(this, "Cuenta o código ya existen.");
            } else {
                Cuenta nuevaCuenta = new Cuenta(codigoContable, nombreCuenta, new TipoCuenta(codTipoCuenta, nombreTipoCuenta));
                boolean success = controlador.crearCuenta(nuevaCuenta);
                if (success) {
                    JOptionPane.showMessageDialog(this, "Cuenta guardada exitosamente.");
                    cargarCuentas();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al guardar la cuenta.");
                }
            }
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        String codigoContable = (String) jComboBoxCodigoContable.getSelectedItem();
        boolean success = controlador.eliminarCuenta(codigoContable);
        if (success) {
            JOptionPane.showMessageDialog(this, "Cuenta eliminada exitosamente.");
            cargarCuentas();
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar la cuenta.");
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuentas().setVisible(true);
            }
        });
    }
    
    private void limpiarCampos() {
        jComboBoxCodigoContable.setSelectedItem("");
        jComboBoxNombreCuenta.setSelectedItem("");
        jComboBoxTipodeCuenta.setSelectedItem("");
    }

    private void cargarCuentas() {
        List<Cuenta> cuentas = controlador.leerTodasCuentas();
        cuentas.forEach(System.out::println);
        System.out.println(cuentas.size());
        jComboBoxNombreCuenta.removeAllItems();
        jComboBoxCodigoContable.removeAllItems();
        //jComboBoxTipodeCuenta.removeAllItems();
        DefaultTableModel model = (DefaultTableModel) jTableCuenta.getModel();
        model.setRowCount(0);
        for (Cuenta cuenta : cuentas) {
            jComboBoxNombreCuenta.addItem(cuenta.getNombreCuenta());
            jComboBoxCodigoContable.addItem(cuenta.getCodigoContable());
            //jComboBoxTipodeCuenta.addItem(cuenta.getTipoCuenta().getNombreTipoCuenta());
            //model.addRow(new Object[]{cuenta.getCodigoContable(), cuenta.getNombreCuenta(), cuenta.getTipoCuenta().getNombreTipoCuenta()});
            model.addRow(new Object[]{cuenta.getCodigoContable(), cuenta.getNombreCuenta(), cuenta.getTipoCuenta().getNombreTipoCuenta()});
        }
    }

    private void cargarTipoCuentas() {
        List<TipoCuenta> tipoCuentas = controladorT.leerTodosTipoCuenta2();
        tipoCuentas.forEach(System.out::println);
        System.out.println("El tamaño de la lista tipoctas es: " + tipoCuentas.size());
        jComboBoxTipodeCuenta.removeAllItems();
        for (TipoCuenta tipoCuenta : tipoCuentas) {
            //jComboBoxTipodeCuenta.addItem(tipoCuenta.getNombreTipoCuenta());
            jComboBoxTipodeCuenta.addItem(tipoCuenta.getNombreTipoCuenta());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLeer;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JComboBox<String> jComboBoxCodigoContable;
    private javax.swing.JComboBox<String> jComboBoxNombreCuenta;
    private javax.swing.JComboBox<String> jComboBoxTipodeCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCuenta;
    // End of variables declaration//GEN-END:variables
}
