/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.frontend.vista;

import com.mycompany.frontend.controlador.TipoCuentaControlador;
import com.mycompany.frontend.modelo.TipoCuenta;
import com.mycompany.frontend.modelo.GrupoGPNP;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author German
 */
public class TipodeCuenta extends javax.swing.JFrame {
    
    private TipoCuentaControlador controlador;
    private List<GrupoGPNP> gruposGPNP;

    /**
     * Creates new form TipodeCuenta
     */
    public TipodeCuenta() {
        initComponents();
        controlador = new TipoCuentaControlador();
        cargarTipoCuenta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxNombreTipoCuenta = new javax.swing.JComboBox<>();
        jButtonNuevo = new javax.swing.JButton();
        jButtonLeer = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTipodeCuenta = new javax.swing.JTable();
        jComboBoxNombreGrupoGPNP = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tipo de cuenta");

        jLabel1.setText("Tipo de cuenta:");

        jComboBoxNombreTipoCuenta.setEditable(true);
        jComboBoxNombreTipoCuenta.setToolTipText("");
        jComboBoxNombreTipoCuenta.setName(""); // NOI18N
        jComboBoxNombreTipoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNombreTipoCuentaActionPerformed(evt);
            }
        });

        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        jButtonLeer.setText("Leer");
        jButtonLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeerActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jTableTipodeCuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo de Cuenta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableTipodeCuenta);

        jComboBoxNombreGrupoGPNP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DeBalance", "DeResultados" }));
        jComboBoxNombreGrupoGPNP.setEnabled(false);
        jComboBoxNombreGrupoGPNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNombreGrupoGPNPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jComboBoxNombreTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButtonNuevo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonLeer)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonGuardar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxNombreGrupoGPNP, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxNombreTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevo)
                    .addComponent(jButtonLeer)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonEliminar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBoxNombreGrupoGPNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxNombreTipoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNombreTipoCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNombreTipoCuentaActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        // TODO add your handling code here:
        jComboBoxNombreTipoCuenta.setSelectedItem("");
        jComboBoxNombreTipoCuenta.setEnabled(true);
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeerActionPerformed
        // TODO add your handling code here:
        cargarTipoCuenta();
    }//GEN-LAST:event_jButtonLeerActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        String nombreTipoCuenta = (String) jComboBoxNombreTipoCuenta.getSelectedItem();
        if (nombreTipoCuenta == null || nombreTipoCuenta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo Tipo de Cuenta no puede estar vacío.");
            return;
        }

        List<TipoCuenta> tipoCuentas = controlador.leerTodosTipoCuenta();
        for (TipoCuenta tipoCuenta : tipoCuentas) {
            if (tipoCuenta.getNombreTipoCuenta().equals(nombreTipoCuenta)) {
                JOptionPane.showMessageDialog(this, "Tipo de cuenta ya existe.");
                return;
            }
        }

        TipoCuenta nuevaTipoCuenta = new TipoCuenta(nombreTipoCuenta);
        if (controlador.crearTipoCuenta(nuevaTipoCuenta)) {
            cargarTipoCuenta();
        } else {
            JOptionPane.showMessageDialog(this, "Error al crear el Tipo de Cuenta.");
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        String nombreTipoCuenta = (String) jComboBoxNombreTipoCuenta.getSelectedItem();
        if (controlador.eliminarTipoCuenta(nombreTipoCuenta)) {
            cargarTipoCuenta();
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar el Tipo de Cuenta.");
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jComboBoxNombreGrupoGPNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNombreGrupoGPNPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNombreGrupoGPNPActionPerformed

    /**
     * @param args the command line arguments
     */
private void cargarTipoCuenta() {
    List<TipoCuenta> tipoCuentas = controlador.leerTodosTipoCuenta();
    tipoCuentas.forEach(System.out::println);
    System.out.println("El tamaño de la lista es: " + tipoCuentas.size());
    jComboBoxNombreTipoCuenta.removeAllItems();
    DefaultTableModel model = (DefaultTableModel) jTableTipodeCuenta.getModel();
    model.setRowCount(0);
    for (TipoCuenta tipoCuenta : tipoCuentas) {
            jComboBoxNombreTipoCuenta.addItem(tipoCuenta.getNombreTipoCuenta());
            model.addRow(new Object[]{tipoCuenta.getNombreTipoCuenta()});
    }
    gruposGPNP= controlador.leerTodosGruposGPNP();
    jComboBoxNombreGrupoGPNP.removeAllItems();
    for (GrupoGPNP grupoGPNP: gruposGPNP){
    //jComboBoxNombreGrupoGPNP.addItem(grupoGPNP.getNombreGrupoGPNP());
    }
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipodeCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipodeCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipodeCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipodeCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipodeCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLeer;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JComboBox<String> jComboBoxNombreGrupoGPNP;
    private javax.swing.JComboBox<String> jComboBoxNombreTipoCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTipodeCuenta;
    // End of variables declaration//GEN-END:variables
}
